

#' Apply continuous enrollment function
#'
#' @description
#' `ContinuousEnrollment()` is developed to extract individuals who are continuously enrolled over a certain period of time in claims databases.
#' The function only works on enrollment datasets generated by [arrow::open_dataset()]
#'
#' @param enrollment_data An arrow dataset. The dataset must have at least 3 columns: The individual ID (`ENROLID`), start of enrollment date (`DTSTART`),
#' and end of enrollment date (`DTEND`).
#' @param data A tibble or data frame containing at least two columns: The individual ID (`ENROLID`) and a column for the index date (specified in the `index_date_var` argument)
#' @param days_after Number of days of continuous enrollment after the index date.
#' @param days_before Number of days of continuous enrollment before the index date.
#' @param max_gap Number of gap days allowed
#' @param index_date_var The name of the variable indicating the index date
#'
#' @return The output will have the same columns as the input `data`, but with excluding patients who were not continuously enrolled based on the user's specification.
#' @export
#'
ContinuousEnrollment <- function(
    enrollment_data,
    data,
    days_after = 0,
    days_before,
    max_gap = 0,
    index_date_var
)
{
  suppressMessages(
    suppressWarnings(
      a <-  enrollment_data |>
        select(ENROLID, DTSTART, DTEND) |>
        filter(ENROLID %in% unique(data$ENROLID)) |>
        to_duckdb() |>
        arrange(ENROLID, DTSTART) |>
        group_by(ENROLID) |>
        mutate(gap_days = abs((lag(DTEND) - DTSTART)+1) ) |>
        mutate(continuous_cov_start = if_else(gap_days > max_gap | is.na(gap_days), DTSTART, NA)) |>
        mutate(cont_enrol = ifelse(is.na(continuous_cov_start),0,1)) |>
        mutate(episode = cumsum(cont_enrol)) |>
        group_by(ENROLID, episode) |>
        summarise(start_cont_enrol = min(DTSTART),
                  end_cont_enrol = max(DTEND)) |>
        collect()
    )
  )
  suppressMessages(
    suppressWarnings(
      b <- data |>
        mutate(pre_cont_enrol_period_begin = {{index_date_var}} - days_before) |>
        mutate(post_cont_enrol_period_end = {{index_date_var}} + days_after) |>
        left_join(a) |>
        arrange(ENROLID) |>
        filter(interval(pre_cont_enrol_period_begin, {{index_date_var}}) %within% interval(start_cont_enrol, end_cont_enrol),
               interval({{index_date_var}}, post_cont_enrol_period_end) %within% interval(start_cont_enrol, end_cont_enrol)
        ) |>
        select(-c(pre_cont_enrol_period_begin, post_cont_enrol_period_end, episode, start_cont_enrol, end_cont_enrol))
    )
  )
  return(b)
}

